version: "3"

services:
  node-microservice:
    build:
      context: ./node-microservice
      dockerfile: Dockerfile
    container_name: node-microservice
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./node-microservice/.env
    volumes:
      - ./node-microservice:/app
    networks:
      - app-network

  flask-microservice:
    build:
      context: ./flask-microservice
      dockerfile: Dockerfile
    container_name: flask-microservice
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - ./flask-microservice/.env
    volumes:
      - ./flask-microservice:/app
    networks:
      - app-network

  nginx-gateway:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-gateway
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - node-microservice
      - flask-microservice

networks:
  app-network:
    name: microservices-network
    driver: bridge
